
import Navbar from "@/components/NavBar";
import "./globals.css";
import Footer from "@/components/Footer";



export const metadata = {
  title: "Car Pk App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative">
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
